### ISSUE TITLE
0.25.1 not found?

### ISSUE THREAD

**Issue by ashmckenzie** [pine/crenv#43]
```
$ crenv install 0.25.1
Resolving Crystal download URL by Remote Cache ... ok
Downloading Crystal binary tarball ...
https://homebrew.bintray.com/bottles/crystal-lang-0.25.1_1.high_sierra.bottle.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    33    0    33    0     0     27      0 --:--:--  0:00:01 --:--:--    27
Cannot read enough bytes from the tarfile at /Users/ash/.anyenv/envs/crenv/plugins/crystal-build/bin/../lib/CrystalBuild/Utils.pm line 44.
No files found for /Users/ash/.anyenv/envs/crenv/cache/0.25.1/crystal-lang-0.25.1_1.high_sierra.bottle.tar.gz at /Users/ash/.anyenv/envs/crenv/plugins/crystal-build/bin/../lib/CrystalBuild/Utils.pm line 45.
ok
Use of uninitialized value $extracted_dir in rename at /Users/ash/.anyenv/envs/crenv/plugins/crystal-build/bin/../lib/CrystalBuild/Installer/Crystal.pm line 91.
Moving the Crystal directory ...faild to move the Crystal directory No such file or directory
```

**Comment by ashmckenzie** [comment]
https://homebrew.bintray.com/bottles/crystal-0.25.1.high_sierra.bottle.tar.gz appears to be the correct URL.

**Comment by kolyaio** [comment]
I have the same problem

**Comment by taylorthurlow** [comment]
I'm also experiencing the same problem installing `0.28.0`.

**Comment by taylorthurlow** [comment]
Ok, I was able to solve the problem after much struggling - I hate Perl.

**This is an issue with `crystal-build`.**

The problem is twofold. Firstly, the format of the extracted Crystal tarball is wrong for GitHub releases. When the tarball was extracted it created a `crystal` folder, and crystal-build was looking for something that matched `crystal-*`. I changed this line:

https://github.com/pine/crystal-build/blob/8a5d14fa45dd44746770c4e985474d08b64c5f2d/lib/CrystalBuild/Downloader/Crystal.pm#L20

To read `'crystal'` instead.

This seemingly solved the problem but it actually now was failing to build shards. The long story short of it is that the newly installed crystal had an extra directory layer, so it extracted to `versions/0.28/0.28` instead. I fixed this by tweaking this line:

https://github.com/pine/crystal-build/blob/8a5d14fa45dd44746770c4e985474d08b64c5f2d/lib/CrystalBuild/Installer/Crystal.pm#L35

To read:

~~~perl
my $full_path = $extracted_dir . "/" . $crystal_version;
$self->_move($full_path, $install_dir);
~~~

This just tacks on the version number so it extracts properly.

The install went fine after that. I'm going to fork this but I'm not really sure what impacts my changes might have to older versions and such, so I won't open a PR.

EDIT: Fork here: https://github.com/taylorthurlow/crystal-build

**Comment by taylorthurlow** [comment]
I've fixed the issue (seemingly properly) in the referenced pull request (pine/crystal-build/pull/71).

**Comment by taylorthurlow** [comment]
After further investigation, I solved an issue that seems the same but is not. The URL for 0.25.1 is just wrong, as corrected by @ashmckenzie.

**Comment by pine** [comment]
Hi @taylorthurlow @ashmckenzie @kolyaio. I'm looking for maintainer.

Could you refer the issue if you have a free time? Thank you.

https://github.com/pine/crenv/issues/47
